name: Qodana

on:
  push:
    branches:
      - main
      - stable
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ##
  ## Job: Qodana
  ##
  tools-qodana:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    continue-on-error: true
    timeout-minutes: 30
    steps:
      ## Setup: Checkout Code
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      ## Run Qodana
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@102d021fe8a24d8af48a38a35f96b8ba100baa20 # tag=v5.1.0

      ## Upload SARIF
      - name: 'Upload SARIF Report'
        uses: github/codeql-action/upload-sarif@3e7e3b32d0fb8283594bb0a76cc60a00918b0969 # tag=v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          category: qodana

