name: Sonar

on:
  push:
    branches:
      - main
      - stable
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ##
  ## Job: Sonar
  ##
  tools-sonar:
    runs-on: ubuntu-latest
    steps:
      ## Setup: Checkout Code
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      ## Setup: Java
      - uses: actions/setup-java@16cca5479d7c6b6843f6a6515640ba33c6501543 # tag=v3
        with:
          distribution: 'zulu'
          java-version: '11'

      ## Setup: GraalVM
      - uses: elide-tools/setup-graalvm@48f2bf339ab7d35e31029b1822a213681fdfc42e # tag=5.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'

      ## Setup: Checkout Code
      - name: Cache SonarCloud packages
        uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      ## Prep: Download Caches
      - name: Cache build
        uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3
        with:
          path: |
            ./build
            ./*/build
            ./*/*/build
          key: elide-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            elide-gradle-${{ runner.os }}
            elide-gradle-

      ## Run Sonar
      - name: "Run Sonar"
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1 # tag=v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: |
            build
            test
            sonarqube
            --scan
            -Pelide.ci=true
